baseURL = "https://Dyxmaster.github.io/"
languageCode = "zh-cn"
title = "My Blog"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
